---

- hosts:  webservers
  become: true
  tasks:
    - name: 1.0 - Upgrade All Packages
      shell: apt update -y

    - name: 1.1 - Install Latest Version of Apache
      apt: name=apache2,php,php-mysql,libapache2-mod-php state=latest

    - name: 1.2 - Install Git
      apt: name=git state=present

    - name: 1.3 - Delete Default Localhost File
      file:
        path: /var/www/html/index.html
        state: absent

    - name: 1.4 - Pull Localhost Application via Git
      ansible.builtin.git:
        repo: https://github.com/vjoksimovic/Web-Projekat-2022q2.git
        dest: /var/www/html/
        version: development

    - name: 1.5 - Update reg.php Database Servername
      lineinfile:
        path: /var/www/html/php/reg.php
        search_string: $servername = "localhost";
        line: $servername = "192.168.56.107:3306";
        state: present
        backup: yes
      become: true
   
    - name: 1.6 - Update reg.php Database Username
      lineinfile:
        path: /var/www/html/php/reg.php
        search_string: $username = "ilijaaaa";
        line: $username = "root";
        state: present
        backup: yes
      become: true

    - name: 1.7 - Update reg.php Database Password
      lineinfile:
        path: /var/www/html/php/reg.php
        search_string: $password = "ilija 123";
        line: $password = "root";
        state: present
        backup: yes
      become: true

    - name: 1.8 - Update config.php Database Servername
      lineinfile:
        path: /var/www/html/php/config.php
        search_string: $servername = "localhost";
        line: $servername = "192.168.56.107:3306";
        state: present
        backup: yes
      become: true
   
    - name: 1.9 - Update config.php Database Username
      lineinfile:
        path: /var/www/html/php/config.php
        search_string: $username = "ilijaaaa";
        line: $username = "root";
        state: present
        backup: yes
      become: true

    - name: 1.10 - Update config.php Database Password
      lineinfile:
        path: /var/www/html/php/config.php
        search_string: $password = "ilija 123";
        line: $password = "root";
        state: present
        backup: yes
      become: true

- hosts: dbservers
  become: true
  vars:
    mysql_root_password: root
  tasks:
    - name: 2.0 - Upgrade All Packages
      shell: yum update -y

    - name: 2.1 - Install MariaDB
      yum: name=mariadb-server,MySQL-python state=latest

    - name: 2.2 - Start MariaDB
      service: 
        name: mariadb
        enabled: true
        state: started

    - name: 2.3 - Create a Database User
      mysql_user:
        name: root
        password: root
      # priv: '*.*:ALL'
      # host_all: yes
        state: present
        login_user: root
        login_password: root

    - name: 2.4 - Create a New Database
      mysql_db:
        name: secondopinion
        login_user: root
        login_password: root

  #  - name: 2.4.1 - Grant Database Access to Webserver
  #     community.mysql.mysql_query:
  #      login_user: root
  #      login_password: root
  #      query: RENAME USER 'root'@'192.168.56.108' TO 'root'@'localhost';
 
    - name: 2.5 - Create Table - Customer
      community.mysql.mysql_query:
        login_user: root
        login_password: root
        login_db: secondopinion
        query: CREATE TABLE `customer` (
            `id` int(11) NOT NULL,
            `email` varchar(255) NOT NULL,
            `password` varchar(255) NOT NULL,
            `last_name` varchar(255) DEFAULT NULL,
            `first_name` varchar(255) DEFAULT NULL,
            `gender` varchar(256) NOT NULL
          );

    - name: 2.6 - Create Table - Conversation 
      community.mysql.mysql_query:
        login_db: secondopinion
        login_user: root
        login_password: root
        query: CREATE TABLE `conversation` (
            `id` int(11) UNSIGNED NOT NULL,
            `senderEmail` varchar(256) DEFAULT NULL,
            `receiverEmail` varchar(256) DEFAULT NULL,
            `message` mediumtext
          );

    - name: 2.7 - Open MySQL Port to Webserver 
      command: firewall-cmd --permanent --zone=public --add-port=3306/tcp

    - name: 2.8 - Reload Firewall 
      command: firewall-cmd --reload
