---
# tasks file for webservers
    - name: 1.0 - Upgrade All Packages
      shell: apt update -y

    - name: Webserver
      ansible.builtin.include_role:
        name: web_distrocheck 

    - name: 1.2 - Install Git
      become: true
      action: >
        {{ ansible_pkg_mgr }} name=git state=latest update_cache=yes

    - name: 1.3 - Delete Default Localhost File
      file:
        path: /var/www/html/index.html
        state: absent

    - name: 1.4 - Pull Localhost Application via Git
      ansible.builtin.git:
        repo: https://github.com/vjoksimovic/Web-Projekat-2022q2.git
        dest: /var/www/html/
        version: development

    - name: 1.5 - Update reg.php Database Servername
      lineinfile:
        path: /var/www/html/php/reg.php
        search_string: $servername = "localhost";
        line: $servername = "192.168.56.107:3306";
        state: present
        backup: yes
      become: true
   
    - name: 1.6 - Update reg.php Database Username
      lineinfile:
        path: /var/www/html/php/reg.php
        search_string: $username = "ilijaaaa";
        line: $username = "root";
        state: present
        backup: yes
      become: true

    - name: 1.7 - Update reg.php Database Password
      lineinfile:
        path: /var/www/html/php/reg.php
        search_string: $password = "ilija 123";
        line: $password = "root";
        state: present
        backup: yes
      become: true

    - name: 1.8 - Update config.php Database Servername
      lineinfile:
        path: /var/www/html/php/config.php
        search_string: $servername = "localhost";
        line: $servername = "192.168.56.107:3306";
        state: present
        backup: yes
      become: true
   
    - name: 1.9 - Update config.php Database Username
      lineinfile:
        path: /var/www/html/php/config.php
        search_string: $username = "ilijaaaa";
        line: $username = "root";
        state: present
        backup: yes
      become: true

    - name: 1.10 - Update config.php Database Password
      lineinfile:
        path: /var/www/html/php/config.php
        search_string: $password = "ilija 123";
        line: $password = "root";
        state: present
        backup: yes
      become: true