---
# tasks file for dbservers
    - name: 2.0 - Upgrade All Packages
      shell: yum update -y

    - name: 2.1 - Install MariaDB
      yum: name=mariadb-server,MySQL-python state=latest

    - name: 2.2 - Start MariaDB
      service: 
        name: mariadb
        enabled: true
        state: started

    - name: 2.3 - Create a Database User
      mysql_user:
        name: veljo
        password: veljo
        host: 192.168.56.108
        state: present
        login_user: root
        login_password: root
        priv: "*.*:ALL"

  #  - name: 2.4 - Give Database Privileges 
  #    community.mysql.mysql_query:
  #      login_user: root
  #      login_password: root
  #      query: GRANT ALL PRIVILEGES ON *.* TO 'veljo'@'%' IDENTIFIED BY 'veljo';


      #  query: BEGIN;
      #    CREATE USER 'veljo'@'localhost' IDENTIFIED BY 'veljo';
      #    GRANT ALL PRIVILEGES ON *.* TO 'veljo'@'localhost' IDENTIFIED BY 'veljo';
      #    END;
  
    - name: 2.5 - Create a New Database
      mysql_db:
        name: secondopinion
        login_user: root
        login_password: root
        
    - name: 2.6 - Create Table - Customer
      community.mysql.mysql_query:
        login_user: root
        login_password: root
        login_db: secondopinion
        query: CREATE TABLE `customer` (
            `id` int(11) NOT NULL,
            `email` varchar(255) NOT NULL,
            `password` varchar(255) NOT NULL,
            `last_name` varchar(255) DEFAULT NULL,
            `first_name` varchar(255) DEFAULT NULL,
            `gender` varchar(256) NOT NULL
          );

    - name: 2.7 - Create Table - Conversation 
      community.mysql.mysql_query:
        login_db: secondopinion
        login_user: root
        login_password: root
        query: CREATE TABLE `conversation` (
            `id` int(11) UNSIGNED NOT NULL,
            `senderEmail` varchar(256) DEFAULT NULL,
            `receiverEmail` varchar(256) DEFAULT NULL,
            `message` mediumtext
          );

    - name: 2.8 - Open MySQL Port to Webserver 
      command: firewall-cmd --permanent --zone=public --add-port=3306/tcp

    - name: 2.9 - Reload Firewall 
      command: firewall-cmd --reload
